/**
 * liveAspectMeanings.ts
 * 
 * Makna 78 kartu tarot Rider-Waite (posisi tegak) dibagi 3 aspek:
 * Hubungan, Karir, Nasib — sumber: arti-tarot-78-rider-waite.md (data lokal, bukan AI).
 * Dipakai khusus untuk Ramalan Live (1 kartu / 3 kartu) agar hasil singkat & padat,
 * cocok ditampilkan di overlay OBS saat live TikTok.
 */

export interface AspectMeaning {
  hubungan: string;
  karir: string;
  nasib: string;
}

export const liveAspectMeanings: Record<string, AspectMeaning> = {
  'major-00': { hubungan: 'Awal baru yang polos, spontanitas, hubungan baru tanpa beban masa lalu.', karir: 'Peluang baru, lompatan karir, ambil risiko dengan semangat petualang.', nasib: 'Babak baru dalam hidup, langkah dengan keyakinan meski belum jelas arahnya.' },
  'major-01': { hubungan: 'Komunikasi kuat, kemampuan memikat pasangan, kepercayaan diri dalam pendekatan.', karir: 'Keahlian dan sumber daya cukup untuk mewujudkan rencana, inisiatif tinggi.', nasib: 'Kekuatan untuk menciptakan realitas sendiri; segala alat sudah tersedia.' },
  'major-02': { hubungan: 'Intuisi tentang pasangan, ada hal tersembunyi/belum terungkap, kedekatan emosional dalam.', karir: 'Gunakan insting, hindari keputusan tergesa, banyak informasi belum terbuka.', nasib: 'Misteri, kebijaksanaan batin, ikuti intuisi bukan logika semata.' },
  'major-03': { hubungan: 'Kesuburan, kehangatan, hubungan penuh cinta dan pertumbuhan.', karir: 'Kreativitas berkembang, hasil kerja membuahkan kelimpahan.', nasib: 'Masa kelimpahan, kemakmuran, dan pertumbuhan alami.' },
  'major-04': { hubungan: 'Stabilitas, komitmen serius, pasangan yang protektif/dominan.', karir: 'Kepemimpinan, struktur, otoritas dan kontrol atas situasi.', nasib: 'Fondasi kokoh, disiplin membawa keteraturan hidup.' },
  'major-05': { hubungan: 'Hubungan konvensional, pernikahan, restu keluarga/tradisi penting.', karir: 'Ikuti aturan/sistem yang ada, mentor membantu, institusi formal.', nasib: 'Jalan tradisional, bimbingan spiritual atau institusional.' },
  'major-06': { hubungan: 'Cinta sejati, keselarasan nilai, pilihan besar dalam hubungan.', karir: 'Kemitraan yang cocok, keputusan penting berdasarkan nilai pribadi.', nasib: 'Persimpangan pilihan, harmoni bila selaras dengan hati nurani.' },
  'major-07': { hubungan: 'Mengejar hubungan dengan tekad, mengatasi perbedaan lewat kemauan kuat.', karir: 'Kemenangan lewat disiplin dan fokus, ambisi terarah.', nasib: 'Kendali penuh atas arah hidup, kemenangan setelah perjuangan.' },
  'major-08': { hubungan: 'Kesabaran, kelembutan menaklukkan konflik, kekuatan batin dalam relasi.', karir: 'Ketekunan mengalahkan tantangan besar, keberanian yang tenang.', nasib: 'Kekuatan sejati datang dari pengendalian diri, bukan paksaan.' },
  'major-09': { hubungan: 'Butuh waktu sendiri, introspeksi sebelum melangkah dalam hubungan.', karir: 'Bekerja mandiri, refleksi diri untuk menemukan arah karir sejati.', nasib: 'Pencarian batin, pencerahan datang lewat kesendirian.' },
  'major-10': { hubungan: 'Perubahan siklus, takdir mempertemukan atau memisahkan.', karir: 'Peluang datang tiba-tiba, siklus naik-turun karir.', nasib: 'Roda takdir berputar; perubahan besar tak terduga.' },
  'major-11': { hubungan: 'Keadilan dan kejujuran, keseimbangan memberi-menerima.', karir: 'Keputusan adil, urusan hukum/kontrak berjalan lancar.', nasib: 'Sebab-akibat berlaku; hasil sesuai perbuatan (karma).' },
  'major-12': { hubungan: 'Masa menunggu, pengorbanan, melihat hubungan dari sudut pandang baru.', karir: 'Situasi tertunda, perlu melepas kendali dan bersabar.', nasib: 'Jeda diperlukan sebelum pencerahan, sudut pandang baru mengubah segalanya.' },
  'major-13': { hubungan: 'Akhir babak lama, transformasi besar dalam hubungan.', karir: 'Perubahan besar/transisi karir, tutup satu bab buka bab lain.', nasib: 'Transformasi tak terelakkan, kelahiran kembali setelah berakhirnya sesuatu.' },
  'major-14': { hubungan: 'Keseimbangan, kesabaran, kompromi yang harmonis.', karir: 'Kolaborasi seimbang, proses bertahap membuahkan hasil.', nasib: 'Harmoni dan moderasi membawa kedamaian jangka panjang.' },
  'major-15': { hubungan: 'Ketergantungan, obsesi, atau hubungan toksik yang mengikat.', karir: 'Terjebak rutinitas/tekanan finansial, sulit lepas dari situasi.', nasib: 'Belenggu diri sendiri; kebebasan ada tapi tidak disadari.' },
  'major-16': { hubungan: 'Keretakan mendadak, kebenaran tersembunyi terungkap.', karir: 'Guncangan besar/PHK mendadak, fondasi lama runtuh.', nasib: 'Kehancuran mendadak yang membuka jalan pembaruan.' },
  'major-17': { hubungan: 'Harapan, kepercayaan pulih, hubungan menyembuhkan luka lama.', karir: 'Inspirasi baru, masa depan cerah setelah masa sulit.', nasib: 'Harapan dan pemulihan; alam semesta mendukung.' },
  'major-18': { hubungan: 'Kebingungan, kecemburuan, ada yang belum jelas/disembunyikan.', karir: 'Situasi tidak pasti, ilusi menutupi kenyataan.', nasib: 'Fase penuh ketidakpastian dan emosi mendalam, ikuti intuisi.' },
  'major-19': { hubungan: 'Kebahagiaan, keterbukaan, hubungan penuh kegembiraan dan kejujuran.', karir: 'Kesuksesan, pengakuan, energi positif membuahkan hasil.', nasib: 'Masa penuh cahaya, keberuntungan dan vitalitas.' },
  'major-20': { hubungan: 'Rekonsiliasi, evaluasi hubungan, kesempatan kedua.', karir: 'Panggilan hidup baru, evaluasi pencapaian untuk melangkah maju.', nasib: 'Kebangkitan, keputusan besar yang mengubah arah hidup.' },
  'major-21': { hubungan: 'Keutuhan, hubungan yang lengkap dan memuaskan.', karir: 'Pencapaian puncak, siklus sukses selesai dengan sempurna.', nasib: 'Penyelesaian siklus besar, pencapaian tujuan hidup.' },
  'wands-01': { hubungan: 'Gairah baru, ketertarikan yang membara.', karir: 'Ide/peluang baru penuh semangat untuk memulai.', nasib: 'Percikan awal energi kreatif dan potensi besar.' },
  'wands-02': { hubungan: 'Merencanakan masa depan bersama, mempertimbangkan pilihan.', karir: 'Perencanaan strategis, melihat gambaran besar.', nasib: 'Berdiri di persimpangan, menimbang langkah selanjutnya.' },
  'wands-03': { hubungan: 'Menantikan perkembangan, hubungan jarak jauh yang menjanjikan.', karir: 'Ekspansi, hasil dari rencana mulai terlihat.', nasib: 'Pandangan ke depan, peluang datang dari luar.' },
  'wands-04': { hubungan: 'Perayaan, pertunangan/pernikahan, kestabilan yang membahagiakan.', karir: 'Pencapaian dirayakan, fondasi kerja yang solid.', nasib: 'Harmoni dan perayaan atas pencapaian.' },
  'wands-05': { hubungan: 'Perselisihan kecil, persaingan mendapatkan perhatian.', karir: 'Kompetisi, konflik pendapat di tempat kerja.', nasib: 'Gesekan yang mendorong pertumbuhan lewat tantangan.' },
  'wands-06': { hubungan: 'Kebanggaan bersama pasangan, diakui publik.', karir: 'Kemenangan, pengakuan atas kerja keras.', nasib: 'Kesuksesan dan pengakuan yang layak diterima.' },
  'wands-07': { hubungan: 'Mempertahankan hubungan dari gangguan pihak ketiga.', karir: 'Mempertahankan posisi di tengah persaingan ketat.', nasib: 'Keteguhan diperlukan untuk melindungi apa yang dimiliki.' },
  'wands-08': { hubungan: 'Perkembangan cepat, kabar/pertemuan datang tiba-tiba.', karir: 'Segala sesuatu bergerak cepat, proyek melaju pesat.', nasib: 'Percepatan peristiwa, momentum besar sedang terjadi.' },
  'wands-09': { hubungan: 'Kewaspadaan dari luka masa lalu, tapi bertahan.', karir: 'Hampir mencapai tujuan meski lelah, tetap gigih.', nasib: 'Ketahanan diuji sebelum garis akhir.' },
  'wands-10': { hubungan: 'Beban tanggung jawab dalam hubungan terasa berat.', karir: 'Kelebihan beban kerja, hampir mencapai hasil dengan lelah.', nasib: 'Tanggung jawab besar yang menuntut ketahanan.' },
  'wands-11': { hubungan: 'Ketertarikan baru yang antusias dan eksploratif.', karir: 'Ide segar, semangat belajar hal baru.', nasib: 'Berita/kabar baru penuh semangat petualangan.' },
  'wands-12': { hubungan: 'Pendekatan berapi-api, penuh gairah namun impulsif.', karir: 'Aksi cepat, keberanian mengambil risiko besar.', nasib: 'Perjalanan/perubahan mendadak penuh energi.' },
  'wands-13': { hubungan: 'Percaya diri, hangat, dan menarik secara alami.', karir: 'Kepemimpinan karismatik, mandiri dan berdaya.', nasib: 'Kekuatan pribadi dan pesona yang membuka jalan.' },
  'wands-14': { hubungan: 'Pasangan visioner, pemimpin yang penuh semangat.', karir: 'Kepemimpinan visioner, keberanian mengambil keputusan besar.', nasib: 'Kendali penuh atas visi dan tujuan hidup.' },
  'cups-01': { hubungan: 'Cinta baru, keterbukaan emosional yang murni.', karir: 'Kepuasan emosional dari pekerjaan, kolaborasi tulus.', nasib: 'Awal baru secara emosional dan spiritual.' },
  'cups-02': { hubungan: 'Ikatan romantis yang seimbang, saling melengkapi.', karir: 'Kemitraan yang harmonis, kerja sama saling menguntungkan.', nasib: 'Kesatuan dan hubungan timbal balik yang baik.' },
  'cups-03': { hubungan: 'Perayaan bersama teman/komunitas, dukungan sosial.', karir: 'Kolaborasi tim yang menyenangkan, hasil kerja bersama.', nasib: 'Kebahagiaan yang dirayakan bersama orang lain.' },
  'cups-04': { hubungan: 'Kebosanan, kurang menghargai apa yang dimiliki.', karir: 'Rasa tidak puas, kesempatan terabaikan.', nasib: 'Perlu introspeksi untuk melihat peluang di depan mata.' },
  'cups-05': { hubungan: 'Kekecewaan, berduka atas kehilangan tapi masih ada harapan.', karir: 'Kegagalan yang menyakitkan, fokus berlebihan pada hal negatif.', nasib: 'Masa berduka, namun tersisa peluang untuk bangkit.' },
  'cups-06': { hubungan: 'Nostalgia, cinta masa lalu, kehangatan masa kecil.', karir: 'Bantuan dari koneksi lama, kembali ke jalur familiar.', nasib: 'Kenangan masa lalu memengaruhi arah masa depan.' },
  'cups-07': { hubungan: 'Banyak pilihan/godaan, sulit menentukan yang nyata.', karir: 'Terlalu banyak opsi, perlu fokus dan realistis.', nasib: 'Ilusi dan angan-angan, perlu kejelasan arah.' },
  'cups-08': { hubungan: 'Melepaskan hubungan yang tak lagi memuaskan.', karir: 'Meninggalkan pekerjaan demi pencarian makna lebih dalam.', nasib: 'Perjalanan mencari sesuatu yang lebih bermakna.' },
  'cups-09': { hubungan: 'Kepuasan emosional, keinginan tercapai.', karir: 'Kesuksesan yang memuaskan, hasil kerja keras terbayar.', nasib: 'Kartu "harapan terkabul", kebahagiaan dan kepuasan.' },
  'cups-10': { hubungan: 'Kebahagiaan keluarga, keharmonisan jangka panjang.', karir: 'Kepuasan menyeluruh, keseimbangan hidup-kerja tercapai.', nasib: 'Kebahagiaan sejati dan keharmonisan hidup.' },
  'cups-11': { hubungan: 'Ungkapan cinta yang polos, pesan romantis.', karir: 'Ide kreatif baru, intuisi dalam pekerjaan.', nasib: 'Kabar emosional atau kejutan yang menyentuh hati.' },
  'cups-12': { hubungan: 'Romantisme, pendekatan penuh perasaan, lamaran.', karir: 'Menawarkan ide dengan pesona, mengejar visi kreatif.', nasib: 'Perjalanan emosional/spiritual mengikuti hati.' },
  'cups-13': { hubungan: 'Empati mendalam, pengertian, kasih sayang tulus.', karir: 'Intuisi kuat dalam pekerjaan, kepekaan terhadap orang lain.', nasib: 'Kebijaksanaan emosional membimbing jalan hidup.' },
  'cups-14': { hubungan: 'Kematangan emosional, pasangan yang bijaksana dan tenang.', karir: 'Kepemimpinan tenang, mengelola emosi dengan baik di kerja.', nasib: 'Penguasaan diri secara emosional membawa kedamaian.' },
  'swords-01': { hubungan: 'Kejujuran baru, kejelasan tentang perasaan.', karir: 'Ide brilian, terobosan pemikiran baru.', nasib: 'Kebenaran terungkap, awal kejelasan mental.' },
  'swords-02': { hubungan: 'Kebuntuan, sulit mengambil keputusan tentang hubungan.', karir: 'Jalan buntu, perlu keputusan sulit yang dihindari.', nasib: 'Kebimbangan, perlu keberanian menghadapi kenyataan.' },
  'swords-03': { hubungan: 'Patah hati, pengkhianatan, kesedihan mendalam.', karir: 'Kritik menyakitkan, kegagalan yang berat.', nasib: 'Masa duka yang mendalam namun perlu dilalui.' },
  'swords-04': { hubungan: 'Butuh jeda untuk memulihkan diri, istirahat dari konflik.', karir: 'Waktu istirahat diperlukan sebelum melanjutkan.', nasib: 'Pemulihan dan kontemplasi sebelum melangkah lagi.' },
  'swords-05': { hubungan: 'Konflik yang merugikan semua pihak, ego menang.', karir: 'Kemenangan yang tidak etis, perselisihan tempat kerja.', nasib: 'Kemenangan kosong, perlu introspeksi tentang cara mencapainya.' },
  'swords-06': { hubungan: 'Meninggalkan masa sulit, transisi menuju ketenangan.', karir: 'Pindah ke situasi yang lebih baik, transisi karir.', nasib: 'Perjalanan menuju kedamaian setelah masa sulit.' },
  'swords-07': { hubungan: 'Ketidakjujuran, ada yang disembunyikan dari pasangan.', karir: 'Strategi licik atau ada yang bekerja sendiri diam-diam.', nasib: 'Kehati-hatian diperlukan, ada tipu daya di sekitar.' },
  'swords-08': { hubungan: 'Merasa terjebak, sulit melihat jalan keluar.', karir: 'Merasa terbatas oleh keadaan, padahal solusi tersedia.', nasib: 'Belenggu pikiran sendiri; kebebasan sebenarnya dekat.' },
  'swords-09': { hubungan: 'Kecemasan, kekhawatiran berlebihan tentang hubungan.', karir: 'Stres dan insomnia karena tekanan kerja.', nasib: 'Kecemasan mental yang perlu dikelola dengan bijak.' },
  'swords-10': { hubungan: 'Akhir yang menyakitkan, titik terendah hubungan.', karir: 'Kegagalan total, namun menjadi titik balik.', nasib: 'Akhir dari suatu siklus yang menyakitkan sebelum kebangkitan.' },
  'swords-11': { hubungan: 'Komunikasi terbuka, ingin tahu lebih dalam tentang pasangan.', karir: 'Ide baru penuh rasa ingin tahu, perlu kehati-hatian.', nasib: 'Kabar/informasi baru yang perlu diverifikasi.' },
  'swords-12': { hubungan: 'Pendekatan cepat dan tegas, terkadang terlalu terburu-buru.', karir: 'Aksi cepat dan ambisius, kadang kurang perhitungan.', nasib: 'Perubahan cepat yang menuntut ketegasan.' },
  'swords-13': { hubungan: 'Kejujuran tegas, batasan yang jelas dalam hubungan.', karir: 'Ketegasan dan kejelasan berpikir, keputusan objektif.', nasib: 'Kebijaksanaan tajam yang lahir dari pengalaman.' },
  'swords-14': { hubungan: 'Pasangan rasional, komunikasi berdasarkan logika dan kejujuran.', karir: 'Kepemimpinan berdasarkan logika, otoritas intelektual.', nasib: 'Kejelasan pikiran membimbing keputusan besar.' },
  'pentacles-01': { hubungan: 'Peluang hubungan yang stabil dan menjanjikan secara materi.', karir: 'Peluang finansial/pekerjaan baru yang menjanjikan.', nasib: 'Awal kemakmuran dan kestabilan baru.' },
  'pentacles-02': { hubungan: 'Menyeimbangkan hubungan dengan kesibukan lain.', karir: 'Mengelola banyak tugas/proyek sekaligus dengan fleksibel.', nasib: 'Keseimbangan hidup di tengah perubahan.' },
  'pentacles-03': { hubungan: 'Kerja sama membangun hubungan bersama-sama.', karir: 'Kolaborasi tim yang membuahkan hasil berkualitas.', nasib: 'Kerja keras kolektif membangun sesuatu yang bertahan lama.' },
  'pentacles-04': { hubungan: 'Posesif, sulit berbagi emosi/sumber daya.', karir: 'Berpegang erat pada stabilitas, kurang fleksibel.', nasib: 'Keamanan yang dipegang terlalu kuat bisa membatasi.' },
  'pentacles-05': { hubungan: 'Masa sulit bersama, dukungan diperlukan.', karir: 'Kesulitan finansial, kehilangan pekerjaan/kesempatan.', nasib: 'Masa kekurangan, namun bantuan ada di sekitar.' },
  'pentacles-06': { hubungan: 'Saling memberi dan menerima dengan seimbang.', karir: 'Kedermawanan, bantuan finansial datang atau diberikan.', nasib: 'Keseimbangan antara memberi dan menerima dalam hidup.' },
  'pentacles-07': { hubungan: 'Menilai hasil investasi emosional dalam hubungan.', karir: 'Evaluasi hasil kerja, kesabaran menunggu hasil panen.', nasib: 'Masa evaluasi sebelum menentukan langkah berikutnya.' },
  'pentacles-08': { hubungan: 'Berusaha keras memperbaiki dan merawat hubungan.', karir: 'Fokus pada keterampilan, kerja keras dan dedikasi.', nasib: 'Penguasaan keahlian membawa hasil jangka panjang.' },
  'pentacles-09': { hubungan: 'Mandiri secara emosional, nyaman sendiri maupun berpasangan.', karir: 'Kemandirian finansial, hasil kerja keras dinikmati sendiri.', nasib: 'Kemapanan yang dicapai lewat usaha pribadi.' },
  'pentacles-10': { hubungan: 'Stabilitas jangka panjang, keluarga besar yang harmonis.', karir: 'Kesuksesan finansial jangka panjang, warisan yang kokoh.', nasib: 'Kemakmuran yang mapan dan diwariskan.' },
  'pentacles-11': { hubungan: 'Ketertarikan yang serius dan berkomitmen jangka panjang.', karir: 'Peluang belajar baru, langkah awal menuju kestabilan.', nasib: 'Awal dari rencana matang menuju kemapanan.' },
  'pentacles-12': { hubungan: 'Pasangan setia, konsisten, dapat diandalkan.', karir: 'Kerja keras metodis, hasil bertahap namun pasti.', nasib: 'Ketekunan dan kesabaran membawa hasil nyata.' },
  'pentacles-13': { hubungan: 'Kehangatan praktis, mengurus pasangan dengan penuh perhatian.', karir: 'Manajemen yang baik, keseimbangan kerja dan kehidupan.', nasib: 'Kemakmuran yang dibangun dengan kepedulian dan kepraktisan.' },
  'pentacles-14': { hubungan: 'Pasangan mapan, memberi rasa aman secara materi.', karir: 'Kesuksesan bisnis, kepemimpinan yang stabil dan berpengalaman.', nasib: 'Puncak kemapanan materi dan pengaruh yang kokoh.' },
};
